### ISSUE TITLE
用mklink 链接后，再次用dirlink 又会链接一次

### ISSUE THREAD

**Issue by brucmao** [appotry/PTtool#2]
第一次用mklink 
```
SRC="/volume1/Downloads/src"
DST="/volume1/Downloads/dst"
```

源目录   /volume1/Downloads/src/Anime/Cells At Work S02 2021 1080p WEB-DL H264 AAC-wev123 硬链接到 /volume1/Downloads/dst/Anime/Cells At Work S02 2021 1080p WEB-DL H264 AAC-wev123 
硬链接后，修改了目录 dst/Anime/Cells At Work S02 2021 1080p WEB-DL H264 AAC-wev123  为 dst/Anime/Cells at Work   ，并增加了子文件夹，如下（主要是方便infuse 读取封面）
![Snipaste_2021-11-27_22-29-43](https://user-images.githubusercontent.com/6119652/143685658-6cc84291-1278-4bb3-ac98-5a75c653b43d.png)

ps: /volume1/Downloads/ 挂载在windows 为 Y:

后面由于 /volume1/Downloads/src/Anime  目录下增加了新的文件，于是使用 dirlink
```
SRC="/volume1/Downloads/src/Anime"
DST="/volume1/Downloads/dst/Anime"
```
发现Cells At Work S02 2021 1080p WEB-DL H264 AAC-wev123  这个文件夹又被硬链接了
dirlink 硬链接的时候，应该判断/volume1/Downloads/src/Anime/Cells At Work S02 2021 1080p WEB-DL H264 AAC-wev123  目录下的islinked.lk 文件，怎么又链接了该目录呢

**Comment by appotry** [comment]
这两个脚本用其中一个就行了
