### ISSUE TITLE
如果源目录下只有文件没有目录，使用dirlink.sh会报错

### ISSUE THREAD

**Issue by HYQ307** [appotry/PTtool#3]
源目录：/home/down/u2-48460 ,该目录下只有一个*.iso文件
硬链接目标目录: /home/up/u2-48460

运行脚本dirlink.sh "/home/down/u2-48460" "/home/up/u2-48460" 会报错，麻烦修正下谢谢。

**Comment by HYQ307** [comment]
mklink.sh也报错：
./mklinh.sh "/root/src" "/root/dest"
/root/src下只有test.sh文件
![image](https://user-images.githubusercontent.com/27661594/182419759-49bd7d01-1083-4275-bdc8-c7c6da737333.png)

**Comment by appotry** [comment]
@HYQ307 第一个问题，你需要使用mklink.sh，而不是dirlink.sh

第二个问题是 mklink.sh原来的版本没有添加支持参数，刚刚修改了添加支持参数输入，下载新版

**Comment by HYQ307** [comment]
> @HYQ307 第一个问题，你需要使用mklink.sh，而不是dirlink.sh
> 
> 第二个问题是 mklink.sh原来的版本没有添加支持参数，刚刚修改了添加支持参数输入，下载新版

我测试下，不过突然发现linux自带硬链接工具，折腾这么久的脚本……

cp -l source dest -R

**Comment by HYQ307** [comment]
![image](https://user-images.githubusercontent.com/27661594/182597135-3eb8ed99-b32a-4c0f-9ffa-d56983c193d9.png)

还是有问题哦

**Comment by appotry** [comment]
本地测速没问题，确保是下载的最新版本。你在root目录下面工作，应该是需要root权限的，检查文件目录权限是否正常
```
mklink.sh ./src ./dst
```

**Comment by appotry** [comment]
@HYQ307 问题解决了？ 如果解决了，就关闭这个issue了
