### ISSUE TITLE
ptpp添加的任务没有分类怎么解？

### ISSUE THREAD

**Issue by Pollo3470** [appotry/PTtool#4]
ptpp无法在添加任务时自动设置分类，无法配合autolink

**Comment by appotry** [comment]
PTPP有个下载目录设置，把你常用的下载目录都设置进去
后面PTPP添加任务的时候，就可以选择这些事先设置的下载目录了

**Comment by Pollo3470** [comment]
我知道可以选择下载目录，但是任务是没有分类的，autolink不是要特定的分类才会触发吗？

**Comment by appotry** [comment]
> 我知道可以选择下载目录，但是任务是没有分类的，autolink不是要特定的分类才会触发吗？

你如果使用autolink，这个是和qbit完成时运行外部程序触发的，readme中有说明的

**Comment by appotry** [comment]
另一个解决方法，使用qbittorrent下载ptpp任务，选择对应分类目录，然后再去qbittorrent中设置分类‘
qbittorrent下载完自动触发脚本
