### ISSUE TITLE
mklink限定xMB以下复制文件就是把参数中的1直接改为x吗？

### ISSUE THREAD

**Issue by zwjie12** [appotry/PTtool#6]
默认限定1MB的参数是FILEGIG=1000000c，项目说明中举例2MB是FILEGIG=2000000c，是不是就这样以此类推，限定多少MB就把首位数字改为多少？
比如限定10MB就是FILEGIG=10000000c？没大明白。

**Comment by appotry** [comment]
FILEGIG=10M 可以直接这么写 

1000000c 表示 1000000 字节，也就是 1MB。在 find 命令中，可以使用 c 表示字节，k 表示千字节，M 表示兆字节，G 表示吉字节等，这些后缀可以用来指定 -size 选项所匹配的文件大小。

如果要计算具体的字节大小，可以使用以下转换关系：

1 字节（Byte）= 8 比特（Bit）
1 千字节（KB）= 1024 字节
1 兆字节（MB）= 1024 KB
1 吉字节（GB）= 1024 MB

因此，如果要查找大于 10MB 的文件，可以使用 -size +10M，如果要查找大于 100MB 的文件，可以使用 -size +100M。
