### ISSUE TITLE
【求教】硬链接的空间占用问题

### ISSUE THREAD

**Issue by chingxuds** [appotry/PTtool#8]
作者你好：
本人使用硬链接方式链接了一个目录，将Organized链接到Source上，按理说硬链接不会造成实际的空间占用，本人通过du命令验证也是如此，但是群晖系统却将文件空间计算了两次，请问什么情况会导致如此问题？是否与群晖的文件系统和RAID方式有关？

du命令查看实际空间占用：
<img width="710" alt="image" src="https://github.com/appotry/PTtool/assets/3142486/986a9f00-adee-4414-934e-07cf11a4e39d">

群晖系统计算空间占用：
<img width="750" alt="image" src="https://github.com/appotry/PTtool/assets/3142486/6be51c3b-cb76-4e8a-a6e8-0925e3aaa226">

DSM文件系统格式：Btrfs，RAID类别：SHR（Synology Hybrid RAID）

**Comment by appotry** [comment]
这个应该属于群辉系统目录空间占用计算方式的问题，计算方式不同导致重复计算了大小

linux原生文件系统基本都支持硬链接，和是否使用raid无关。

```
man du
...

       -L, --dereference
              dereference all symbolic links

       -l, --count-links
              count sizes many times if hard linked
```

**Comment by chingxuds** [comment]
> 这个应该属于群辉系统目录空间占用计算方式的问题，计算方式不同导致重复计算了大小
> 
> linux原生文件系统基本都支持硬链接，和是否使用raid无关。
> 
> ```
> man du
> ...
> 
>        -L, --dereference
>               dereference all symbolic links
> 
>        -l, --count-links
>               count sizes many times if hard linked
> ```

非常感谢答复，我也觉得是群晖系统的问题，已经给群晖技术支援提交问题工单了，但愿他们能接收处理。现在天天提醒我空间不足。
